# Generated by Django 4.2.2 on 2023-06-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0002_auto_20230331_2020"),
    ]

    operations = [
        migrations.CreateModel(
            name="blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="")),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(max_length=50000)),
            ],
            options={
                "ordering": ["-date_added"],
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
